/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProviderSetupRouteImport } from './routes/provider-setup'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackingIdRouteImport } from './routes/tracking.$id'
import { Route as RatingIdRouteImport } from './routes/rating.$id'
import { Route as ProviderActiveRouteImport } from './routes/provider.active'
import { Route as ProviderDetailIdRouteImport } from './routes/provider-detail.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderSetupRoute = ProviderSetupRouteImport.update({
  id: '/provider-setup',
  path: '/provider-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingIdRoute = TrackingIdRouteImport.update({
  id: '/tracking/$id',
  path: '/tracking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingIdRoute = RatingIdRouteImport.update({
  id: '/rating/$id',
  path: '/rating/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderActiveRoute = ProviderActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderDetailIdRoute = ProviderDetailIdRouteImport.update({
  id: '/provider-detail/$id',
  path: '/provider-detail/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/provider': typeof ProviderRouteWithChildren
  '/provider-setup': typeof ProviderSetupRoute
  '/register': typeof RegisterRoute
  '/provider-detail/$id': typeof ProviderDetailIdRoute
  '/provider/active': typeof ProviderActiveRoute
  '/rating/$id': typeof RatingIdRoute
  '/tracking/$id': typeof TrackingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/provider': typeof ProviderRouteWithChildren
  '/provider-setup': typeof ProviderSetupRoute
  '/register': typeof RegisterRoute
  '/provider-detail/$id': typeof ProviderDetailIdRoute
  '/provider/active': typeof ProviderActiveRoute
  '/rating/$id': typeof RatingIdRoute
  '/tracking/$id': typeof TrackingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/provider': typeof ProviderRouteWithChildren
  '/provider-setup': typeof ProviderSetupRoute
  '/register': typeof RegisterRoute
  '/provider-detail/$id': typeof ProviderDetailIdRoute
  '/provider/active': typeof ProviderActiveRoute
  '/rating/$id': typeof RatingIdRoute
  '/tracking/$id': typeof TrackingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/favorites'
    | '/home'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/provider'
    | '/provider-setup'
    | '/register'
    | '/provider-detail/$id'
    | '/provider/active'
    | '/rating/$id'
    | '/tracking/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/favorites'
    | '/home'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/provider'
    | '/provider-setup'
    | '/register'
    | '/provider-detail/$id'
    | '/provider/active'
    | '/rating/$id'
    | '/tracking/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/favorites'
    | '/home'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/provider'
    | '/provider-setup'
    | '/register'
    | '/provider-detail/$id'
    | '/provider/active'
    | '/rating/$id'
    | '/tracking/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRoute
  ProviderRoute: typeof ProviderRouteWithChildren
  ProviderSetupRoute: typeof ProviderSetupRoute
  RegisterRoute: typeof RegisterRoute
  ProviderDetailIdRoute: typeof ProviderDetailIdRoute
  RatingIdRoute: typeof RatingIdRoute
  TrackingIdRoute: typeof TrackingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-setup': {
      id: '/provider-setup'
      path: '/provider-setup'
      fullPath: '/provider-setup'
      preLoaderRoute: typeof ProviderSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/$id': {
      id: '/tracking/$id'
      path: '/tracking/$id'
      fullPath: '/tracking/$id'
      preLoaderRoute: typeof TrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/$id': {
      id: '/rating/$id'
      path: '/rating/$id'
      fullPath: '/rating/$id'
      preLoaderRoute: typeof RatingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/active': {
      id: '/provider/active'
      path: '/active'
      fullPath: '/provider/active'
      preLoaderRoute: typeof ProviderActiveRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider-detail/$id': {
      id: '/provider-detail/$id'
      path: '/provider-detail/$id'
      fullPath: '/provider-detail/$id'
      preLoaderRoute: typeof ProviderDetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProviderRouteChildren {
  ProviderActiveRoute: typeof ProviderActiveRoute
}

const ProviderRouteChildren: ProviderRouteChildren = {
  ProviderActiveRoute: ProviderActiveRoute,
}

const ProviderRouteWithChildren = ProviderRoute._addFileChildren(
  ProviderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRoute,
  ProviderRoute: ProviderRouteWithChildren,
  ProviderSetupRoute: ProviderSetupRoute,
  RegisterRoute: RegisterRoute,
  ProviderDetailIdRoute: ProviderDetailIdRoute,
  RatingIdRoute: RatingIdRoute,
  TrackingIdRoute: TrackingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
